### ISSUE TITLE
Add Hawthorne disturbance view to models.py

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#24]
This can be done with inspectdb (can you do just one table? or will it have to run all?) Or it can be entered manually (should be easy, not many columns). It should be done after issue #22 / PR #23 are resolved. Happy to tackle this manually, but @znmeb you may already have a good process for this too.

**Comment by znmeb** [comment]
The view is in the RDS database now.

**Comment by jbeyer16** [comment]
Great! I think you ran inspectdb last time, is it okay to run it again? I can try it out, I can also update models.py manually.

**Comment by jbeyer16** [comment]
I figured it out. I'll update the models.py file with the `disturbance_stops` view model definition.
