### ISSUE TITLE
disturbance_stop doesn't have id field

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#29]
Using the default swagger interface, we cannot explore disturbance_stop by `id`, because there is no `id` field. We'll either have to make one, or remove this capability.

**Comment by jbeyer16** [comment]
I think maybe we should add one. I can't query anything at the moment. See this: 

>Hi @datchpenguin, thanks for this.
Django does depend on an id field existing. This can be in a couple of ways:
Set one of your fields to primary_key=True - this will map .id to that field
Generate an id field in your view SQL that Django can use to uniquely identify
Set a generic value like 1 AS id in your SQL if you're not interested in the ID field
Usually, it's considered good to determine a primary key for your view so you can look it up, in which case, 1 or 2 would be needed. If you never use a primary key, then just do 3 and that should work fine for most cases.
>

**Comment by znmeb** [comment]
Yep - I think I can copy the ID from the source table.

**Comment by znmeb** [comment]
Well - looks like it needs to be a primary key for Django, which means I need to change it from a materialized view to a table. That's easy to do ... it'll probably be tomorrow night before I can update the RDS site

**Comment by jbeyer16** [comment]
Sounds good to me.

**Comment by znmeb** [comment]
Fixed in RDS and in the code. `disturbance_stops` is now a table with a primary key `id` which has the same value as the `id` of the `bus_all_stops` row it came from.
