### ISSUE TITLE
Django Worker Timeout on Queries

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#30]
For each of our three endpoints (in `add_disturbance` branch), querying for a specific id returns a result, but querying by limit / offset times out with a `CRITICAL: WORKER TIMEOUT` message. The timeout appears to occur after roughly 60 seconds of waiting for a result.

Example of working queries:
http://localhost:8000/v1/transportation-systems/toad/bus-passenger-stops/19/
http://localhost:8000/v1/transportation-systems/toad/bus-all-stops/6/
http://localhost:8000/v1/transportation-systems/toad/disturbance-stops/7/

Example of query that will hang:
http://localhost:8000/v1/transportation-systems/toad/disturbance-stops/?limit=10&offset=1

This behavior was not seen when the API was built on a local (also smaller) database.

`add_disturbance`should be able to be run to replicate these issues, provided the`.env` file is updated with the correct credentials.

Providing the limit / offset capability is not mandatory for our graphics, but I'm still having trouble even with the filter i've built in `line`. I'll keep at some of the filtering to see if I can get one working, but for now @znmeb @BrianHGrant any thoughts?

**Comment by znmeb** [comment]
Why the "Invalid" tag?

My thought is that we need to instrument the code and get CloudWatch logs for the server when we're running a query unless there's some gunicorn logging that will solve this.

**Comment by jbeyer16** [comment]
Okay I'm making some progress. If I limit the result number using an index in the view aka [:100] I can return results. So I think there's something with the number of objects needing to be returned taking too long.

Invalid because the description was "this doesn't seem right" and it didn't seem right?

**Comment by jbeyer16** [comment]
Seems I can get 50,000 but not 500,000. Not sure how many total will fall in our vis. I'm going to make this more of a question for now.

**Comment by jbeyer16** [comment]
Seems part of it comes from the first query where django gets a count, then the second where it gets the result.

`(25.728) SELECT COUNT(*) FROM (SELECT "disturbance_stops"."id" AS Col1 FROM "disturbance_stops" WHERE (EXTRACT('month' FROM "disturbance_stops"."opd_date") >= 9 AND EXTRACT('month' FROM "disturbance_stops"."opd_date") <= 9 AND "disturbance_stops"."line_id" IN (10) AND "disturbance_stops"."pattern_direction" = 'I' AND "disturbance_stops"."start_quarter_hour" >= 6.0 AND "disturbance_stops"."end_quarter_hour" <= 7.0)  LIMIT 5) subquery; args=(9, 9, 10, 'I', 6.0, 7.0)`

There's an admin option around `show_full_result_count`

> The default of show_full_result_count=True generates a query to perform a full count on the table which can be expensive if the table contains a large number of rows.

**Comment by znmeb** [comment]
Ah - is the SQL that Django generates shown anywhere?

**Comment by jbeyer16** [comment]
what you see above is basically it. I only get to see the SQL it generates if it's able to complete the query in time though :(

**Comment by znmeb** [comment]
That's OK - paste it into a pgAdmin4 query tool connected to the database and try "Explain analyze" The database will run the query and show you what all the steps were!

**Comment by jbeyer16** [comment]
That would be very helpful. Not knowing that, I've been re-building and running adding each part in. So far I think the "line_id__in=<LINES>" is a tough one.

**Comment by znmeb** [comment]
The "Explain analyze" will show opportunities for indexing columns. The only index at the moment is the `event_no_trip` used in the join that made the table. And the primary keys, which are all IDs.

**Comment by znmeb** [comment]
```
SELECT COUNT(*) FROM (
	SELECT "disturbance_stops"."id" AS Col1 
	FROM "disturbance_stops" 
	WHERE (
		EXTRACT('month' FROM "disturbance_stops"."opd_date") >= 9 
		AND EXTRACT('month' FROM "disturbance_stops"."opd_date") <= 9 
		AND "disturbance_stops"."line_id" IN (10) 
		AND "disturbance_stops"."pattern_direction" = 'I' 
		AND "disturbance_stops"."start_quarter_hour" >= 6.0 
		AND "disturbance_stops"."end_quarter_hour" <= 7.0
	)
) AS harry_the_subquery;
```

The count is 2018. How long did it run? Partitioned by month on my workstation, with some indexes:
```
Successfully run. Total query runtime: 369 msec.
1 rows affected.
```

On RDS with the old database:
```
Successfully run. Total query runtime: 36 secs 791 msec. 1 rows affected.
--
And the count is only 16 on RDS, not 2018

Any idea why the counts would be different?

**Comment by jbeyer16** [comment]
No idea, outside of if the databases contained different data? Not sure why that'd be the case ...

**Comment by znmeb** [comment]
I'm going to add some performance measurement / tuning options to the local development database container, so we can tweak things without having to restart a server on Amazon ;-) It'll probably be Tuesday before it's done.

**Comment by jbeyer16** [comment]
If needed, it seems there is a timeout setting (default 30s) within the `gunicorn_conf.py` file we could modify.

**Comment by jbeyer16** [comment]
#51 these issues are related now,
