### ISSUE TITLE
Update repo from Cookiecutter template

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#4]
Brian is still working on pushing some fixes to the cookiecutter template. There are two outstanding PRs as of right now. Once those are approved / merged in, we will need to update our repo with the new template (needed to have it work properly).

**Comment by znmeb** [comment]
Yeah - I have some of the fixes in https://github.com/hackoregon/2019-transportation-systems-backend/pull/2 so we might as well merge everything in that branch and test with it.
