### ISSUE TITLE
Deployed API container can't see RDS database

### ISSUE THREAD

**Issue by znmeb** [hackoregon/2019-transportation-systems-backend#50]
Symptom is that `docker-entrypoint.sh` crashes in the migrations. The error message implies it's trying to connect via a Unix socket in the API container, not to the RDS system.

**Comment by jbeyer16** [comment]
We've been able to bypass this by commenting out the `if` statements at the beginning of the `docker-entrypoint.sh` but this is likely not a long term solution.

**Comment by znmeb** [comment]
It may be - we may want to leave it this way in our repo, since we'll never need to go back to local API now. It's the "backend cookiecutter" where the local API container needs to work ;-)
