### ISSUE TITLE
railPassengerStops not returning anything

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#52]
With a call to `http://service.civicpdx.org/transportation2019/v1/toad/railPassengerStops/`
nothing comes back 
```json
{
  "count": 0,
  "next": null,
  "previous": null,
  "results": {
    "type": "FeatureCollection",
    "features": []
  }
}```

**Comment by znmeb** [comment]
It turns out I didn't load a couple of months of rail passenger stops into the database. I'm rebuilding it now and will restore it some time tomorrow. So this may go away after I do.

**Comment by znmeb** [comment]
This may be an issue with the primary key - it is on a bunch of columns and there's no serial `id` column. The same is true for `bus_passenger_stops`. If I change this we'll need to change `models.py`.

**Comment by znmeb** [comment]
This may be causing both the missing responses and performance issues: https://github.com/hackoregon/2019-transportation-data-science/issues/44
