### ISSUE TITLE
Locally debugging the API

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#56]
This is going to be a bit of a journey. The ultimate goal is to be able to run the API locally with the same branch that's deployed to help debug issues.

tl;dr - I can get the deployable API running locally as well with slight modifications, but I have no knowledge of any wider effects of these changes.

Right now tag `v0.2.4` is deployed, and master reflects that tag. The API is up [here](http://service.civicpdx.org/transportation2019/v1/schema/). 

[This](http://service.civicpdx.org/transportation2019/v1/toad/trafficSignals/
) call works as expected.

[This](http://service.civicpdx.org/transportation2019/v1/toad/tmRouteStops/
) call returns a `500` error, but no further information (debug = False).

So I wanted to uncover more info to debug that `500` error. 

## 1st Try
* ./bin/build.sh -d
* ./bin/start.sh -d
```shell
api_1  | /code/bin/get-ssm-parameters.sh: line 18: aws: command not found
api_1  | /code/bin/get-ssm-parameters.sh: line 18: jq: command not found
2019-transportation-systems-backend_api_1 exited with code 127
```
In the current edition of `docker-entrypoint.sh` the `if` statement is commented out so the `get-ssm-parameters.sh` is called by default. So here I'll just comment out calling that script, and the echos that follow.
```shell
#if [ ! "${DEBUG}" ] && [ ! "${TRAVIS}" ]; then
  # source /code/bin/get-ssm-parameters.sh
  # echo POSTGRES_NAME: "${POSTGRES_NAME}"
  # echo POSTGRES_HOST: "${POSTGRES_HOST}"
  # echo POSTGRES_PORT: "${POSTGRES_PORT}"
#fi
```

## 2nd Try
* ./bin/build.sh -d
* ./bin/start.sh -d
```shell
api_1  | ModuleNotFoundError: No module named 'health_check'
2019-transportation-systems-backend_api_1 exited with code 1
```
Missing a library. I'll add `django-health-check` to the `development.txt` file.

## 3rd Try
* ./bin/build.sh -d
* ./bin/start.sh -d
```shell
api_1  | ModuleNotFoundError: No module named 'psutil'
2019-transportation-systems-backend_api_1 exited with code 1
```
Missing a library. I'll add `psutil` to the `development.txt` file.

## 4th Try
* ./bin/build.sh -d
* ./bin/start.sh -d
```shell
api_1  | Run server...
api_1  | [2019-08-10 22:10:47 +0000] [16] [INFO] Starting gunicorn 19.9.0
api_1  | [2019-08-10 22:10:47 +0000] [16] [INFO] Listening at: http://0.0.0.0:8000 (16)
api_1  | [2019-08-10 22:10:47 +0000] [16] [INFO] Using worker: sync
api_1  | [2019-08-10 22:10:47 +0000] [16] [INFO] Server is ready. Spawning workers
api_1  | [2019-08-10 22:10:47 +0000] [19] [INFO] Booting worker with pid: 19
```
Up and running! So I navigate to `localhost:8000` - django is running. 
Now I navigate to `localhost:8000/transportation2019/v1/schema/` and I get a `404` page not found error
```html
Using the URLconf defined in backend.urls, Django tried these URL patterns, in this order:

admin/
The current path, v1/transportation-systems/schema, didn't match any of these.
```
Weird, Django seems to only see the `admin/` url, which isn't a part of my schema. To debug this further, I attach VSCode to the container to get full access to the files. Under `/backend/urls.py` I see that `admin/` shows up only when the import of local urls fails.
```python
try:
    from src_files.local_settings.urls import *
except ImportError:
    urlpatterns = [
        path('admin/', admin.site.urls),
    ]
```
So I open a terminal in the container, run `python manage.py shell` and try that import statement. Here's the error it returns:

```python
ImportError: Could not import 'rest_framework.schemas.coreapi.AutoSchema' for API setting 'DEFAULT_SCHEMA_CLASS'. ModuleNotFoundError: No module named 'rest_framework.schemas.coreapi'.
```

It appears that `AutoSchema` cannot be found. After investigating this one a while, the end result was that I found `AutoSchema` could be imported from `rest_framework.schemas` but not `rest_framework.schemas.coreapi` because `coreapi` doesn't seem to exist there.

So I changed the `DEFAULT_SCHEMA_CLASS` to reflect this:

```python
REST_FRAMEWORK = {
    ...
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.AutoSchema",
}
```

## 5th Try
* ./bin/build.sh -d
* ./bin/start.sh -d
```shell
api_1  | Run server...
api_1  | [2019-08-10 22:21:51 +0000] [17] [INFO] Starting gunicorn 19.9.0
api_1  | [2019-08-10 22:21:51 +0000] [17] [INFO] Listening at: http://0.0.0.0:8000 (17)
api_1  | [2019-08-10 22:21:51 +0000] [17] [INFO] Using worker: sync
api_1  | [2019-08-10 22:21:51 +0000] [17] [INFO] Server is ready. Spawning workers
api_1  | [2019-08-10 22:21:51 +0000] [20] [INFO] Booting worker with pid: 20
api_1  | 192.168.16.1 [10/Aug/2019:22:22:38 +0000] GET /transportation2019/v1/schema/  HTTP/1.1 200 15051 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36 0.069276
```
Looks like it's running locally now!

So now when I try my problematic endpoint, I get the following error message, that allows me to see where I messed up. Hooray!

```
ProgrammingError at /transportation2019/v1/toad/tmRouteStops/
column tm_route_stops.direction does not exist
LINE 1: ...m_route_stops"."ogc_fid", "tm_route_stops"."rte", "tm_route_...
```

What was the point of all this? Not sure. But I wanted to document this process in case others ran into it, or in case this is an issue that needs to be fixed in this way or some other way. 

@znmeb @BrianHGrant tagging you for visibility. Happy to discuss further as needed.

**Comment by znmeb** [comment]
Should "we" assign you to this? ;-)

**Comment by jbeyer16** [comment]
Sure! but likely I'll close it as a no fix - just didn't know where else to document it

**Comment by znmeb** [comment]
I'm going to do my local testing with a "native" database from now on - I've got enough room on the SSD for it and it will be up when the API container starts, eliminating the need for the "Is PostgreSQL alive?" loop in `docker-entrypoint.sh`. I don't know how this would work for other people though; they may not have / want a local native PostgreSQL.

Current database is about 36 GB.

**Comment by jbeyer16** [comment]
On my end I'm more concerned about the API than the DB, so I'm okay connecting to RDS and working off what I know is the production DB. I think the use case you've outline for yourself makes sense though.
