### ISSUE TITLE
Add exception handling to views.py

### ISSUE THREAD

**Issue by benleelawrence** [hackoregon/2019-transportation-systems-backend#58]
@jbeyer16 figured out how to add exception handling to the Server response after entering in an invalid parameter..  
Before: 
![image](https://user-images.githubusercontent.com/5599941/62995272-aba74400-be14-11e9-8cc1-f1826fc39454.png)

After: 
![image](https://user-images.githubusercontent.com/5599941/62995283-b661d900-be14-11e9-8c2d-7a0e500588d1.png)

Add this exception handling to all parameters.

**Comment by benleelawrence** [comment]
@jbeyer16 I've made these changes but need to request write access to the repo.  I also noticed that entering an invalid integer in the directions parameter returns a:
TypeError: Failed to fetch

Do you think we should add the same exception handling for TypeError?

**Comment by jbeyer16** [comment]
Closing for now, as a chunk of this got merged in. We probably could extend this to a `TypeError` as well, maybe we open a new issue specific to that if we want to go after it.
