### ISSUE TITLE
Add endpoint for ncdb_sample_transportation_commute table

### ISSUE THREAD

**Issue by znmeb** [hackoregon/2019-transportation-systems-backend#61]

**Comment by nam20485** [comment]
I can create the endpoint as soon as the geometry column is ready. @znmeb  Who is the consumer that can answer the question about which option to use for the geometry column?

**Comment by znmeb** [comment]
I've asked in Slack - tract boundary is what we're going with. I have the table on my workstation but haven't uploaded it to RDS yet.

**Comment by znmeb** [comment]
Table is live in the database: table name is `ncdb_sample_transportation_commute`. The geometry column is census tract boundaries `geom_multpoly_4326`. 

All the census tracts from the Portland - Vancouver - Hillsboro area are there; boolean column `opp_zone` is true for census tracts that are opportunity zones.

I still do not have the code book for the "t_*" columns.

**Comment by nam20485** [comment]
Created PR #67 to resolve this issue.
