### ISSUE TITLE
require year and month for busPassengerStops and railPassengerStops API endpoints

### ISSUE THREAD

**Issue by znmeb** [hackoregon/2019-transportation-systems-backend#64]

**Comment by znmeb** [comment]
Reopening

**Comment by znmeb** [comment]
We also need to rebuild the index - it got dropped in a recent database rebuild

**Comment by jbeyer16** [comment]
@znmeb Right now pgAdmin is showing the same index on both `busPassengerStops` and `railPassengerStops`, that index being the service_date_idx. Are you talking about rebuilding an index on a difference column?

**Comment by znmeb** [comment]
Yes - it needs an index on the columns we're filtering on. It had one but I accidentally dropped it in the latest database build.
