### ISSUE TITLE
staticfiles directory is checked in to source control

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-transportation-systems-backend#66]
Did you guys check the staticfiles directory into source control intentionally? 

These files are generated each time the image is built and are not usually checked into source control.

Is there any reason not to remove them?

@jbeyer16 @znmeb @bhgrant8  @BrianHGrant @benleelawrence

**Comment by znmeb** [comment]
Fine with me to remove them - should they be in the cookiecutter repo .gitignore then?

**Comment by nam20485** [comment]
> should they be in the cookiecutter repo .gitignore then?

Yes. The currently-checkedin `staticfiles/` directory will be removed, and added to `.gitignore`.

**Comment by znmeb** [comment]
deployed
