### ISSUE TITLE
New endpoint for "busstop_catchment_zone_with_census_attribs" table

### ISSUE THREAD

**Issue by znmeb** [hackoregon/2019-transportation-systems-backend#75]
Table is live in RDS - sample (as CSV) attached

**Comment by znmeb** [comment]
[busstop_catchment_zone_with_census_attribs.csv.txt](https://github.com/hackoregon/2019-transportation-systems-backend/files/3576112/busstop_catchment_zone_with_census_attribs.csv.txt)

**Comment by jbeyer16** [comment]
Filters on `rte`, `dir` and `stop_id` - return GeoJSON
