### ISSUE TITLE
Remove bin folder

### ISSUE THREAD

**Issue by jbeyer16** [hackoregon/2019-transportation-systems-backend#79]
By moving to the newer deployment strategy (`scripts`) folder, the `bin` folder is no longer needed.

**Comment by jbeyer16** [comment]
@znmeb are you okay with this?

**Comment by znmeb** [comment]
How do we do a development build - `bin/build.sh -d` and `bin/start.sh -d` if we remove `bin`?

**Comment by jbeyer16** [comment]
All those scripts still exist, they're just in a different folder now. Instead of `bin/build.sh -d` and `bin/start.sh -d` they are located at `scripts/build-run/build.sh -d` and `scripts/build-run/start.sh -d`

**Comment by znmeb** [comment]
OK - just update the docs then

**Comment by jbeyer16** [comment]
- [ ] Remove `bin` folder from repo
- [ ] Update docs with new path to scripts
