### ISSUE TITLE
Add stop name and total_ons_and_offs to busAmRushSummary and busPmRushSummary endpoints

### ISSUE THREAD

**Issue by benleelawrence** [hackoregon/2019-transportation-systems-backend#88]
To produce similar maps as the Bokeh plots at https://github.com/hackoregon/2019-transportation-data-science/blob/master/notebooks/3.0-bll-api-bus-summary-interactive-bokeh.ipynb
Front end needs these additional fields added to the `busAmRushSummary` and `busPmRushSummary` endpoints:
1. `total_ons_and_offs`: sum of `total_ons` + `total_offs`
2. `stop_name`: The stop name for the associated `location_id`

**Comment by jbeyer16** [comment]
@benleelawrence rail as well?

**Comment by jbeyer16** [comment]
@znmeb we may need to make this be a part of the database.

**Comment by jbeyer16** [comment]
We could pretty easy sum the two columns, but the stop name will require a join

**Comment by benleelawrence** [comment]
Might as well do rail too to be consistent. I'm also not sure how they are going to aggregate the statistics by stop since there are multiple rows for lines and direction, but I think Curt said it's possible.

**Comment by znmeb** [comment]
OK - yeah, this needs a join but I think it can go into the scripts that generate the summaries. Any reason we need the stop names - that's a little tricky given that some stops aren't currently in `tm_route_stops`

**Comment by znmeb** [comment]
Darn!

```
SELECT DISTINCT location_id FROM bus_am_rush_summary
WHERE location_id NOT IN (
	SELECT ogc_fid FROM trimet_gis.tm_route_stops
)
AND location_id NOT IN (
	SELECT location_id FROM passenger_census_stop_locations
);
```

```
"location_id"
14075
14067
13932
13969
13977
13927
14042
14006
13911
13934
13912
14036
14066
13943
13983
13963
14046
11496
13962
14015
14034
14056
14002
14064
13953
13942
14053
13990
13986
13948
13967
14003
14058
14040
13940
13976
13971
14008
14028
13984
13972
14018
13642
14060
13994
14009
14035
13938
13993
14054
14061
13965
14029
14074
13973
13974
13956
13929
14071
14007
14000
13995
13985
14039
13928
13926
14048
9535
14069
14051
13980
13964
13978
14019
13959
13941
14052
13991
13949
13999
13933
14073
14041
13966
14045
14047
13961
14049
13939
13946
13954
13968
13945
14055
13944
14068
14001
13937
13988
14032
14038
14043
14037
14057
13970
13924
13960
14005
13992
13951
13989
14033
13958
13952
14031
13957
13955
13801
13931
13981
14030
13925
14004
13975
13950
13947
14044
13935
14059
13930
13936
```

**Comment by benleelawrence** [comment]
I don't think stop names are completely necessary, I think it would just look better in a visual. I'm seeing some of those stop ids in `tm_route_stops`. Should that be an `OR` statement instead of `AND`?

**Comment by znmeb** [comment]
If it had a name in either one I'd have a name for it, so AND is what I want. Let me see if the names are in the newer passenger census tables.

**Comment by benleelawrence** [comment]
That makes sense, maybe there is a white space issue or something? I'm seeing some of those stop IDs in `tmRouteStops`:
![image](https://user-images.githubusercontent.com/5599941/64563703-d8ac2100-d304-11e9-9794-2eba0bec3bae.png)

**Comment by znmeb** [comment]
I redid the table - it's down to 18 missing names. I can live with that

```

14006
--
13912
14058
14008
13994
13995
13926
13999
14073
14004
14075
13911
14060
14061
14074
14007
9535
14001
```

**Comment by benleelawrence** [comment]
Awesome, thanks!

**Comment by jbeyer16** [comment]
`total_ons` and `total_offs` appear in bus and rail AM / PM rush summaries but stop names not yet
